name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
     - "apps/editor/**"
  pull_request:
    branches: [ "main" ]
    paths:
     - "apps/editor/**"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: apps/editor
      run: cargo build --verbose
    - name: Run tests
      working-directory: apps/editor
      run: cargo test --verbose
